name: GitHub my profile summary cards

on:
# 更新タイミングを一旦任意のタイミングにしてみる
#  schedule: # Runs at 4am JST
#    - cron: '30 19 * * *'
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    name: Update my github metrics
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          # token permissions: https://github.com/vn7n24fzkq/github-profile-summary-cards/wiki/Toturial#change-github-action-token
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}